### ISSUE TITLE
NotImplementedError: Operator RandomUniform not implemented.

### ISSUE THREAD

**Issue by mnboos** [apache/incubator-tvm#2591]
The following problem occures when trying to compile an ONNX model in a linux environment. Are there any plans when this operator will be implemented?

```
Shape: Differently implemented in NNVM as a bypass (dummy operator)
Traceback (most recent call last):
  File "compile_model.py", line 54, in <module>
    sym, params = nnvm.frontend.from_onnx(onnx_model)
  File "/usr/tvm/nnvm/python/nnvm/frontend/onnx.py", line 967, in from_onnx
    sym, params = g.from_onnx(graph, opset)
  File "/usr/tvm/nnvm/python/nnvm/frontend/onnx.py", line 822, in from_onnx
    op = self._convert_operator(op_name, inputs, attr, opset)
  File "/usr/tvm/nnvm/python/nnvm/frontend/onnx.py", line 926, in _convert_operator
    "Operator {} not implemented.".format(op_name))
NotImplementedError: Operator RandomUniform not implemented.
```

**Comment by mnboos** [comment]
I assume no answer means you have other priorities at the moment?

**Comment by yidawang** [comment]
As of now, I am not aware of a concrete plan of supporting the randomization ops. You can refer to the release roadmap (latest #2623) for major features being (going to be) implemented. You are also highly encouraged to contribute.

**Comment by tqchen** [comment]
Move to #6813
