### ISSUE TITLE
"Bad File Descriptor" whenever trying to run autotvm inside Jupyter notebook

### ISSUE THREAD

**Issue by staticfloat** [apache/incubator-tvm#4046]
Hello there!  I have compiled TVM v0.5 on macOS 10.14, and although everything works great in ipython when run directly from the command-line, when trying to execute TVM code inside of a jupyter notebook kernel, I get the following errors printed out to the `stderr` stream of the notebook kernel:

```
Process Process-3:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/selector_events.py", line 251, in _add_reader
    key = self._selector.get_key(fd)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/selectors.py", line 192, in get_key
    raise KeyError("{!r} is not registered".format(fileobj)) from None
KeyError: '54 is not registered'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sabae/Library/Python/3.7/lib/python/site-packages/tvm-0.5.dev0-py3.7-macosx-10.14-x86_64.egg/tvm/rpc/tracker.py", line 338, in _tracker_server
    handler = TrackerServerHandler(listen_sock, stop_key)
  File "/Users/sabae/Library/Python/3.7/lib/python/site-packages/tvm-0.5.dev0-py3.7-macosx-10.14-x86_64.egg/tvm/rpc/tracker.py", line 279, in __init__
    self._sock.fileno(), _event_handler, self._ioloop.READ)
  File "/Users/sabae/Library/Python/3.7/lib/python/site-packages/tornado/platform/asyncio.py", line 99, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/selector_events.py", line 324, in add_reader
    return self._add_reader(fd, callback, *args)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/selector_events.py", line 254, in _add_reader
    (handle, None))
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/selectors.py", line 522, in register
    self._selector.control([kev], 0, 0)
OSError: [Errno 9] Bad file descriptor

Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sabae/Library/Python/3.7/lib/python/site-packages/tvm-0.5.dev0-py3.7-macosx-10.14-x86_64.egg/tvm/autotvm/measure/measure_methods.py", line 544, in _check
    remote = request_remote(device_key, host, port, priority)
  File "/Users/sabae/Library/Python/3.7/lib/python/site-packages/tvm-0.5.dev0-py3.7-macosx-10.14-x86_64.egg/tvm/autotvm/measure/measure_methods.py", line 511, in request_remote
    tracker = _rpc.connect_tracker(host, port)
  File "/Users/sabae/Library/Python/3.7/lib/python/site-packages/tvm-0.5.dev0-py3.7-macosx-10.14-x86_64.egg/tvm/rpc/client.py", line 414, in connect_tracker
    return TrackerSession((url, port))
  File "/Users/sabae/Library/Python/3.7/lib/python/site-packages/tvm-0.5.dev0-py3.7-macosx-10.14-x86_64.egg/tvm/rpc/client.py", line 205, in __init__
    self._connect()
  File "/Users/sabae/Library/Python/3.7/lib/python/site-packages/tvm-0.5.dev0-py3.7-macosx-10.14-x86_64.egg/tvm/rpc/client.py", line 211, in _connect
    self._sock = base.connect_with_retry(self._addr)
  File "/Users/sabae/Library/Python/3.7/lib/python/site-packages/tvm-0.5.dev0-py3.7-macosx-10.14-x86_64.egg/tvm/rpc/base.py", line 155, in connect_with_retry
    raise sock_err
  File "/Users/sabae/Library/Python/3.7/lib/python/site-packages/tvm-0.5.dev0-py3.7-macosx-10.14-x86_64.egg/tvm/rpc/base.py", line 151, in connect_with_retry
    sock.connect(addr)
TimeoutError: [Errno 60] Operation timed out
```

And I get the following errors printed out to standard out:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-8-3dbbccfb8f99> in <module>
     23         callbacks=[
     24            autotvm.callback.progress_bar(n_trial),
---> 25            autotvm.callback.log_to_file("conv2d_tune.log")
     26         ],
     27     )

~/Library/Python/3.7/lib/python/site-packages/tvm-0.5.dev0-py3.7-macosx-10.14-x86_64.egg/tvm/autotvm/tuner/tuner.py in tune(self, n_trial, measure_option, early_stopping, callbacks)
     90             every measurement pair. See autotvm/tuner/callback.py for some examples.
     91         """
---> 92         measure_batch = create_measure_batch(self.task, measure_option)
     93         n_parallel = getattr(measure_batch, 'n_parallel', 1)
     94         early_stopping = early_stopping or 1e9

~/Library/Python/3.7/lib/python/site-packages/tvm-0.5.dev0-py3.7-macosx-10.14-x86_64.egg/tvm/autotvm/measure/measure.py in create_measure_batch(task, option)
    234     runner = option['runner']
    235 
--> 236     attach_objects = runner.set_task(task)
    237 
    238     # feed device related information from runner to builder

~/Library/Python/3.7/lib/python/site-packages/tvm-0.5.dev0-py3.7-macosx-10.14-x86_64.egg/tvm/autotvm/measure/measure_methods.py in set_task(self, task)
    324         self.port = tracker.port
    325 
--> 326         super(LocalRunner, self).set_task(task)
    327         return server, tracker
    328 

~/Library/Python/3.7/lib/python/site-packages/tvm-0.5.dev0-py3.7-macosx-10.14-x86_64.egg/tvm/autotvm/measure/measure_methods.py in set_task(self, task)
    194             logger.info("Get devices for measurement successfully!")
    195         else:
--> 196             raise RuntimeError("Cannot get remote devices from the tracker. "
    197                                "Please check the status of tracker by "
    198                                "'python -m tvm.exec.query_rpc_tracker --port [THE PORT YOU USE]' "

RuntimeError: Cannot get remote devices from the tracker. Please check the status of tracker by 'python -m tvm.exec.query_rpc_tracker --port [THE PORT YOU USE]' and make sure you have free devices on the queue status.
```

Attempting to run the `query_rpc_tracker` never works (it always times out).  Note that things didn't even work in the console until I changed `localhost` to `0.0.0.0` [here](https://github.com/dmlc/tvm/blob/v0.5/python/tvm/autotvm/measure/measure_methods.py#L316-L321), however that may be because my machine has a slightly non-standard networking setup with wireguard VPNs and whatnot.

If there's anything else I can to do help debug this, please let me know!

**Comment by tqchen** [comment]
I have not tried to run tracker on jupyter, perhaps @merrymercy @vinx13 can comment. from a quick look at the errors. The main reason seems to due to the "Connection time out", then the event handling loop tried to add the bad socket into its set of sockets(which leads to bad file descriptor)

**Comment by vinx13** [comment]
It might be issues with your network setup. Local runner is equivalent to RPC runner with tracker and server running on localhost. You can try using RPC mode by starting RPC tracker and server with your custom address (e.g. `0.0.0.0`

**Comment by tqchen** [comment]
close due to inactive status, please feel free to open a new thread on https://discuss.tvm.ai/
