### ISSUE TITLE
TypeError:'NoneType' object is not callable

### ISSUE THREAD

**Issue by murdockhou** [apache/incubator-tvm#5448]
I have update the tvm to the latest(2020/04/27). After this, I run the code that convert pyorch model to tvm. But get error in the first like this:
```
Traceback (most recent call last):

  File "convert/from_pytorch.py", line 45, in <module>
    from tvm import relay

  File "/media/hsw/E/work/github/tvm_github/python/tvm/relay/__init__.py", line 27, in <module>
    from . import expr_functor

  File "/media/hsw/E/work/github/tvm_github/python/tvm/relay/expr_functor.py", line 25, in <module>
    from .op import Op

  File "/media/hsw/E/work/github/tvm_github/python/tvm/relay/op/__init__.py", line 23, in <module>
    from . import strategy

  File "/media/hsw/E/work/github/tvm_github/python/tvm/relay/op/strategy/__init__.py", line 22, in <module>
    from .generic import *

  File "/media/hsw/E/work/github/tvm_github/python/tvm/relay/op/strategy/generic.py", line 22, in <module>
    import topi

  File "/media/hsw/E/work/github/tvm_github/topi/python/topi/__init__.py", line 46, in <module>
    from . import cuda

  File "/media/hsw/E/work/github/tvm_github/topi/python/topi/cuda/__init__.py", line 26, in <module>
    from .conv2d_int8 import *

  File "/media/hsw/E/work/github/tvm_github/topi/python/topi/cuda/conv2d_int8.py", line 168, in <module>
    _dp4a = dp4a('shared', 'shared', 'local')

  File "/media/hsw/E/work/github/tvm_github/topi/python/topi/cuda/tensor_intrin.py", line 43, in dp4a
    x = te.placeholder((n,), name='x', dtype='int8')

  File "/media/hsw/E/work/github/tvm_github/python/tvm/te/operation.py", line 55, in placeholder
    shape, dtype, name)

  File "tvm/_ffi/_cython/./packed_func.pxi", line 312, in tvm._ffi._cy3.core.PackedFuncBase.__call__

  File "tvm/_ffi/_cython/./packed_func.pxi", line 247, in tvm._ffi._cy3.core.FuncCall

  File "tvm/_ffi/_cython/./packed_func.pxi", line 235, in tvm._ffi._cy3.core.FuncCall3

  File "tvm/_ffi/_cython/./packed_func.pxi", line 158, in tvm._ffi._cy3.core.make_arg

TypeError: 'NoneType' object is not callable

```
I'm confused with that, I run these command line below to update tvm:
```
git pull
git submodule update
cd build
cmake ..
make -j8
```

**Comment by tqchen** [comment]
It is likely that you will also need to update your cython module, by typing `make cython3`, for future questions, please open a new trouble shooting thread on https://discuss.tvm.ai/
