### ISSUE TITLE
[PYTORCH]  pytorch frontend  expand op  bug

### ISSUE THREAD

**Issue by Xuxue1** [apache/incubator-tvm#5575]
In pytorch frontend testcase  modify input_shape and expand shape

```python
def test_forward_expand():
    torch.set_grad_enabled(False)
    input_shape = [3, 1]

    class Expand1(Module):
        def forward(self, *args):
            return args[0].expand((3, 3, 3, 1))

    input_data = torch.rand(input_shape).float()
    verify_model(Expand1().float().eval(), input_data=input_data)
```

Traceback (most recent call last):

  File "tests/python/frontend/pytorch/test_forward.py", line 2109, in <module>
    test_forward_expand()

  File "tests/python/frontend/pytorch/test_forward.py", line 912, in test_forward_expand
    verify_model(Expand1().float().eval(), input_data=input_data)

  File "tests/python/frontend/pytorch/test_forward.py", line 191, in verify_model
    assert_shapes_match(baseline_output, compiled_output)

  File "tests/python/frontend/pytorch/test_forward.py", line 39, in assert_shapes_match
    raise AssertionError(msg.format(tru.shape, est.shape))

AssertionError: Output shapes (3, 3, 3, 1) and (3, 3) don't match

**Comment by masahi** [comment]
Fixed by #5576
