### ISSUE TITLE
[ONNX] check-fail with max_pool2d operator

### ISSUE THREAD

**Issue by areusch** [apache/incubator-tvm#5580]
Steps to reproduce (decompress and place [cifar10.onnx.gz](https://github.com/apache/incubator-tvm/files/4617785/cifar10.onnx.gz) in same dir):
```
import onnx
from tvm import relay

onnx_model = onnx.load('cifar10.onnx')
relay.frontend.from_onnx(onnx_model, {"data": (1, 3, 32, 32)})
```

Traceback:
```
Traceback (most recent call last):

  File "repro.py", line 5, in <module>
    relay.frontend.from_onnx(onnx_model, {"data": (1, 3, 32, 32)})

  File "/Users/andrew/ws/tvm/python/tvm/relay/frontend/onnx.py", line 2009, in from_onnx
    mod, params = g.from_onnx(graph, opset)

  File "/Users/andrew/ws/tvm/python/tvm/relay/frontend/onnx.py", line 1837, in from_onnx
    op = self._convert_operator(op_name, inputs, attr, opset)

  File "/Users/andrew/ws/tvm/python/tvm/relay/frontend/onnx.py", line 1937, in _convert_operator
    sym = convert_map[op_name](inputs, attrs, self._params)

  File "/Users/andrew/ws/tvm/python/tvm/relay/frontend/onnx.py", line 276, in _impl_v1
    custom_check=dimension_constraint())(inputs, attr, params)

  File "/Users/andrew/ws/tvm/python/tvm/relay/frontend/common.py", line 417, in __call__
    return get_relay_op(op_name)(*inputs, **new_attrs)

  File "/Users/andrew/ws/tvm/python/tvm/relay/op/nn/nn.py", line 665, in max_pool2d
    layout, ceil_mode)

  File "/Users/andrew/ws/tvm/python/tvm/_ffi/_ctypes/packed_func.py", line 225, in __call__
    raise get_last_ffi_error()

tvm._ffi.base.TVMError: Traceback (most recent call last):
  [bt] (5) 6   ???                                 0x00007ffee6f45000 0x0 + 140732773191680
  [bt] (4) 5   _ctypes.cpython-37m-darwin.so       0x000000010a46f347 ffi_call_unix64 + 79
  [bt] (3) 4   libtvm.dylib                        0x00000001194d49d8 TVMFuncCall + 72
  [bt] (2) 3   libtvm.dylib                        0x000000011905e7b6 std::__1::__function::__func<void tvm::runtime::TypedPackedFunc<tvm::RelayExpr (tvm::RelayExpr, tvm::Array<tvm::PrimExpr, void>, tvm::Array<tvm::PrimExpr, void>, tvm::Array<tvm::PrimExpr, void>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool)>::AssignTypedLambda<tvm::relay::$_2>(tvm::relay::$_2)::'lambda'(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*), std::__1::allocator<void tvm::runtime::TypedPackedFunc<tvm::RelayExpr (tvm::RelayExpr, tvm::Array<tvm::PrimExpr, void>, tvm::Array<tvm::PrimExpr, void>, tvm::Array<tvm::PrimExpr, void>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool)>::AssignTypedLambda<tvm::relay::$_2>(tvm::relay::$_2)::'lambda'(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)>, void (tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)>::operator()(tvm::runtime::TVMArgs&&, tvm::runtime::TVMRetValue*&&) + 918
  [bt] (1) 2   libtvm.dylib                        0x0000000118b372d8 tvm::Array<tvm::PrimExpr, void> tvm::runtime::TVMPODValue_::AsObjectRef<tvm::Array<tvm::PrimExpr, void> >() const + 696
  [bt] (0) 1   libtvm.dylib                        0x0000000118a55aa9 dmlc::LogMessageFatal::~LogMessageFatal() + 57
  File "../include/tvm/runtime/packed_func.h", line 1378
TVMError: Check failed: type_code_ == kTVMObjectHandle (0 vs. 8) : expected Object but get int
```

**Comment by ryanstout** [comment]
@areusch did you figure this out, I'm seeing the same issue. I'm doing a lookup at one point:

```
out = lut[x.long()]
```

Were you doing something similar? (my onnx model is coming from pytorch)
