### ISSUE TITLE
TVMError: Check failed: nargs == args.size() (3 vs. 4) : Expect 3 arguments but get 4

### ISSUE THREAD

**Issue by oessam** [apache/incubator-tvm#5966]
Can anyone please help with this error.

Traceback (most recent call last):
  File "e:\tvm\tutorials\frontend\from_darknet.py", line 42, in <module>
    from tvm import relay
  File "C:\Users\omara\AppData\Local\Programs\Python\Python36\lib\site-packages\tvm-0.7.dev1-py3.6-win-amd64.egg\tvm\relay\__init__.py", line 29, in <module>
    from . import prelude
  File "C:\Users\omara\AppData\Local\Programs\Python\Python36\lib\site-packages\tvm-0.7.dev1-py3.6-win-amd64.egg\tvm\relay\prelude.py", line 24, in <module>
    from .op.tensor import add, subtract, equal
  File "C:\Users\omara\AppData\Local\Programs\Python\Python36\lib\site-packages\tvm-0.7.dev1-py3.6-win-amd64.egg\tvm\relay\op\__init__.py", line 23, in <module>
    from . import strategy
  File "C:\Users\omara\AppData\Local\Programs\Python\Python36\lib\site-packages\tvm-0.7.dev1-py3.6-win-amd64.egg\tvm\relay\op\strategy\__init__.py", line 22, in <module>
    from .generic import *
  File "C:\Users\omara\AppData\Local\Programs\Python\Python36\lib\site-packages\tvm-0.7.dev1-py3.6-win-amd64.egg\tvm\relay\op\strategy\generic.py", line 22, in <module>
    import topi
  File "C:\Users\omara\AppData\Local\Programs\Python\Python36\lib\site-packages\topi-0.7.dev1-py3.6.egg\topi\__init__.py", line 47, in <module>
    from . import cuda
  File "C:\Users\omara\AppData\Local\Programs\Python\Python36\lib\site-packages\topi-0.7.dev1-py3.6.egg\topi\cuda\__init__.py", line 26, in <module>       
    from .conv2d_int8 import *
  File "C:\Users\omara\AppData\Local\Programs\Python\Python36\lib\site-packages\topi-0.7.dev1-py3.6.egg\topi\cuda\conv2d_int8.py", line 168, in <module>   
    _dp4a = dp4a('shared', 'shared', 'local')
  File "C:\Users\omara\AppData\Local\Programs\Python\Python36\lib\site-packages\topi-0.7.dev1-py3.6.egg\topi\cuda\tensor_intrin.py", line 80, in dp4a      
    z.op, _intrin_func, binds=binds, default_buffer_params=default_buffer_params)
  File "C:\Users\omara\AppData\Local\Programs\Python\Python36\lib\site-packages\tvm-0.7.dev1-py3.6-win-amd64.egg\tvm\te\tensor_intrin.py", line 139, in decl_tensor_intrin
    body = fcompute(binds_list[:len(inputs)], binds_list[len(inputs):])
  File "C:\Users\omara\AppData\Local\Programs\Python\Python36\lib\site-packages\topi-0.7.dev1-py3.6.egg\topi\cuda\tensor_intrin.py", line 70, in _intrin_func
    return _instr(0), _instr(1), _instr(2) # body, reset, update
  File "C:\Users\omara\AppData\Local\Programs\Python\Python36\lib\site-packages\topi-0.7.dev1-py3.6.egg\topi\cuda\tensor_intrin.py", line 65, in _instr    
    new_z = tvm.tir.call_pure_extern('int32', '__dp4a', vec_x, vec_y, prev_z)
  File "C:\Users\omara\AppData\Local\Programs\Python\Python36\lib\site-packages\tvm-0.7.dev1-py3.6-win-amd64.egg\tvm\tir\op.py", line 148, in call_pure_extern
    dtype, Op.get("tir.call_extern"), convert((StringImm(func_name),) + args), Call.PureExtern)
  File "C:\Users\omara\AppData\Local\Programs\Python\Python36\lib\site-packages\tvm-0.7.dev1-py3.6-win-amd64.egg\tvm\tir\expr.py", line 995, in __init__   
    _ffi_api.Call, dtype, op, args, call_type)
  File "C:\Users\omara\AppData\Local\Programs\Python\Python36\lib\site-packages\tvm-0.7.dev1-py3.6-win-amd64.egg\tvm\_ffi\_ctypes\object.py", line 126, in 
__init_handle_by_constructor__
    handle = __init_by_constructor__(fconstructor, args)
  File "C:\Users\omara\AppData\Local\Programs\Python\Python36\lib\site-packages\tvm-0.7.dev1-py3.6-win-amd64.egg\tvm\_ffi\_ctypes\packed_func.py", line 240, in __init_handle_by_constructor__
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  File "E:\tvm\include\tvm/runtime/packed_func.h", line 1248
TVMError: Check failed: nargs == args.size() (3 vs. 4) : Expect 3 arguments but get 4

**Comment by tqchen** [comment]
Please open a new thread on https://discuss.tvm.ai/ this is likely due to a recent refactor and you will need to reinstall the python package after the build
