### ISSUE TITLE
Quantize DeepLabV3+ problem

### ISSUE THREAD

**Issue by zhangzhen507** [apache/incubator-tvm#5979]
I quantize DeepLabV3+ model from Tensorflow and meet the problem here.

The quantization pass has the following problem. 

02-07-2020:01:42:42,719 INFO     [_calibrate.py:99] finding threshold with kl for calibration...
Traceback (most recent call last):
  File "/root/test6_root/zzhen/2020/tvm0620/tutorials/quantize/deeplabv3/quantize_deeplabv3_tf.py", line 330, in <module>
    main()
  File "/root/test6_root/zzhen/2020/tvm0620/tutorials/quantize/deeplabv3/quantize_deeplabv3_tf.py", line 320, in main
    q_mod = quantize(mod, params, data_aware=True, eval_data_list = val_data_list, skip_conv2d_layers=skip_conv2d_layers)
  File "/root/test6_root/zzhen/2020/tvm0620/tutorials/quantize/deeplabv3/quantize_deeplabv3_tf.py", line 232, in quantize
    mod = relay.quantize.quantize(mod, params, dataset=calibrate_dataset(eval_data_list))
  File "/root/test6_root/zzhen/2020/tvm0620/python/tvm/relay/quantize/quantize.py", line 377, in quantize
    mod = quantize_seq(mod)
  File "/root/test6_root/zzhen/2020/tvm0620/python/tvm/ir/transform.py", line 130, in __call__
    return _ffi_transform_api.RunPass(self, mod)
  File "/root/test6_root/zzhen/2020/tvm0620/python/tvm/_ffi/_ctypes/packed_func.py", line 225, in __call__
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  [bt] (8) /root/test6_root/zzhen/2020/tvm0620/build/libtvm.so(tvm::relay::ExprVisitor::VisitExpr_(tvm::relay::IfNode const*)+0x23) [0x7f4f6535dfe3]
  [bt] (7) /root/test6_root/zzhen/2020/tvm0620/build/libtvm.so(tvm::relay::ExprVisitor::VisitExpr(tvm::RelayExpr const&)+0x83) [0x7f4f65363a63]
  [bt] (6) /root/test6_root/zzhen/2020/tvm0620/build/libtvm.so(tvm::relay::ExprFunctor<void (tvm::RelayExpr const&)>::VisitExpr(tvm::RelayExpr const&)+0x105) [0x7f4f6531c7e5]
  [bt] (5) /root/test6_root/zzhen/2020/tvm0620/build/libtvm.so(tvm::relay::ExprVisitor::VisitExpr_(tvm::relay::CallNode const*)+0x3a) [0x7f4f6535ea6a]
  [bt] (4) /root/test6_root/zzhen/2020/tvm0620/build/libtvm.so(tvm::relay::ExprVisitor::VisitExpr(tvm::RelayExpr const&)+0x83) [0x7f4f65363a63]
  [bt] (3) /root/test6_root/zzhen/2020/tvm0620/build/libtvm.so(tvm::relay::ExprFunctor<void (tvm::RelayExpr const&)>::VisitExpr(tvm::RelayExpr const&)+0x105) [0x7f4f6531c7e5]
  [bt] (2) /root/test6_root/zzhen/2020/tvm0620/build/libtvm.so(tvm::relay::TypeVarEVisitor::VisitExpr_(tvm::ConstructorNode const*)+0x4a) [0x7f4f6515803a]
  [bt] (1) /root/test6_root/zzhen/2020/tvm0620/build/libtvm.so(tvm::IRModuleNode::LookupTypeDef(tvm::GlobalTypeVar const&) const+0x132) [0x7f4f64a80d02]
  [bt] (0) /root/test6_root/zzhen/2020/tvm0620/build/libtvm.so(+0x79e2df) [0x7f4f64a7f2df]
  File "/root/test6_root/zzhen/2020/tvm0620/src/ir/module.cc", line 299
TVMError: Check failed: it != type_definitions.end(): There is no definition of List

**Comment by tqchen** [comment]
Please open a new thread on https://discuss.tvm.ai/
