### ISSUE TITLE
TVMError: Check failed: it != type_definitions.end(): There is no definition of static_tensor_float32_*

### ISSUE THREAD

**Issue by nolanliou** [apache/incubator-tvm#6268]
When I convert a PyTorch Bert model to TVM, there is a problem blow
```
  File "tvm/python/tvm/relay/frontend/pytorch.py", line 2673, in from_pytorch
    default_dtype=default_dtype)
  File "/tvm/python/tvm/relay/frontend/pytorch.py", line 2580, in convert_operators
    relay_out = relay_op(inputs, _get_input_types(op_node, default_dtype=default_dtype))
  File "tvm/python/tvm/relay/frontend/pytorch.py", line 255, in _impl
    inferred_shape = _infer_shape(data)
  File "tvm/python/tvm/relay/frontend/common.py", line 486, in infer_shape
    out_type = infer_type(inputs, mod=mod)
  File "tvm/python/tvm/relay/frontend/common.py", line 465, in infer_type
    new_mod = IRModule.from_expr(node)
  File "tvm/python/tvm/ir/module.py", line 222, in from_expr
    return _ffi_api.Module_FromExpr(expr, funcs, defs)
  File "tvm/python/tvm/_ffi/_ctypes/packed_func.py", line 225, in __call__
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  [bt] (8) tvm/build/libtvm.so(tvm::relay::ExprVisitor::VisitExpr_(tvm::relay::CallNode const*)+0x13c) [0x7f21a6454bdc]
  [bt] (7) tvm/build/libtvm.so(tvm::relay::ExprVisitor::VisitExpr(tvm::RelayExpr const&)+0x71) [0x7f21a6457711]
  [bt] (6) tvm/build/libtvm.so(tvm::relay::ExprFunctor<void (tvm::RelayExpr const&)>::VisitExpr(tvm::RelayExpr const&)+0x5b) [0x7f21a64153eb]
  [bt] (5) tvm/build/libtvm.so(tvm::relay::ExprVisitor::VisitExpr_(tvm::relay::CallNode const*)+0x13c) [0x7f21a6454bdc]
  [bt] (4) tvm/build/libtvm.so(tvm::relay::ExprVisitor::VisitExpr(tvm::RelayExpr const&)+0x71) [0x7f21a6457711]
  [bt] (3) tvm/build/libtvm.so(tvm::relay::ExprFunctor<void (tvm::RelayExpr const&)>::VisitExpr(tvm::RelayExpr const&)+0x5b) [0x7f21a64153eb]
  [bt] (2) tvm/build/libtvm.so(tvm::relay::TypeVarEVisitor::VisitExpr_(tvm::ConstructorNode const*)+0x35) [0x7f21a6266505]
  [bt] (1) tvm/build/libtvm.so(tvm::IRModuleNode::LookupTypeDef(tvm::GlobalTypeVar const&) const+0x14a) [0x7f21a5c34a4a]
  [bt] (0) tvm/build/libtvm.so(+0xdc19e7) [0x7f21a5c329e7]
  File "tvm/src/ir/module.cc", line 299
TVMError: Check failed: it != type_definitions.end(): There is no definition of static_tensor_float32_1_4_768_t
```

Part of graph code list below:
```
  _234 = torch.transpose(torch.matmul(scores22, v10), 1, 2)
  h10 = torch.contiguous(_234, memory_format=0)
  _235 = ops.prim.NumToTensor(torch.size(h10, 0))
  _236 = ops.prim.NumToTensor(torch.size(h10, 1))
  input114 = torch.view(h10, [int(_235), int(_236), 768])
  output68 = torch.matmul(input114, torch.t(CONSTANTS.c143))
  input115 = torch.add_(output68, CONSTANTS.c150, alpha=1)
  _237 = torch.dropout(input115, 0.10000000000000001, False)
  input116 = torch.add(input111, _237, alpha=1)
  input117 = torch.layer_norm(input116, [768], CONSTANTS.c3, CONSTANTS.c4, 9.9999999999999998e-13, True)
  output69 = torch.matmul(input117, torch.t(CONSTANTS.c151))
  x94 = torch.add_(output69, CONSTANTS.c152, alpha=1)
  _238 = torch.mul(torch.pow(x94, 3), CONSTANTS.c17)
  _239 = torch.mul(torch.add(x94, _238, alpha=1), CONSTANTS.c18)
  _240 = torch.mul(x94, CONSTANTS.c19)
  _241 = torch.add(torch.tanh(_239), CONSTANTS.c20, alpha=1)
  input118 = torch.mul(_240, _241)
  output70 = torch.matmul(input118, torch.t(CONSTANTS.c153))
  input119 = torch.add_(output70, CONSTANTS.c154, alpha=1)
  _242 = torch.dropout(input119, 0.10000000000000001, False)
  input120 = torch.add(input117, _242, alpha=1)
  encoder_out = torch.layer_norm(input120, [768], CONSTANTS.c3, CONSTANTS.c4, 9.9999999999999998e-13, True)
  _243 = torch.slice(encoder_out, 0, 0, 9223372036854775807, 1)
  input121 = torch.select(_243, 1, 0)
  input122 = torch.addmm(CONSTANTS.c156, input121, torch.t(CONSTANTS.c155), beta=1, alpha=1)
  input123 = torch.tanh(input122)
  input124 = torch.dropout(input123, 0.10000000000000001, False)
  input125 = torch.addmm(CONSTANTS.c158, input124, torch.t(CONSTANTS.c157), beta=1, alpha=1)
  r = torch.softmax(input125, 1, None)
  return torch.to(r, 6, False, False)
```

It failed when converting `slice` OP.

Has anybody seen this question before？

Thanks

**Comment by masahi** [comment]
I can see why this error is happening. We need to pass the Prelude module to `infer_shape`, `mod` argument here https://github.com/apache/incubator-tvm/blob/master/python/tvm/relay/frontend/common.py#L484

See below for how we pass the Prelude mod to `infer_type`. Basically we need a similar function, like `infer_shape_with_prelude`.
https://github.com/apache/incubator-tvm/blob/master/python/tvm/relay/frontend/pytorch.py#L48

A PR welcome.

**Comment by nolanliou** [comment]
The above problem solved to modify the model code.
However, another problem occurred when inferring the type of intermediate tensor and there is a `type cast` operator.

sample code to reproduce the error.
```
import torch
import tvm
from tvm import relay
import tvm.contrib.graph_runtime as runtime

def fn(x):
    y = (x != 0).long()
    y = y.to(dtype=torch.float32)
    y = y[:, 0]
    return y

jit = torch.jit.trace(fn, (torch.ones(4, 5, dtype=torch.int64),))
torch.jit.save(jit, "test.jit")

jit = torch.jit.load("test.jit", map_location=torch.device('cpu'))
jit.eval()

print(jit(torch.ones(4, 5, dtype=torch.int64)))

batch = 1
seq_length = 43
shape_list = [('input', [4, 5])]
input_types = [('input', 'torch.int64')]

print("==========relay=======")
#print(jit.code)
mod, params = relay.frontend.pytorch.from_pytorch(jit,
                                                  shape_list,
                                                  input_types=input_types,  // Add input types, or input type only could be float32
                                                  default_dtype="float32")
```

**Comment by masahi** [comment]
We don't accept `input_types` argument, so I can't run your script. Note that if you save/load your jitted models, dtype will be lost. See https://github.com/pytorch/pytorch/issues/39690 if this is the same problem I raised there.

**Comment by nolanliou** [comment]
Same problem

**Comment by nolanliou** [comment]
Sample code to reproduce the problem of inputs' type not matching.
```
import numpy as np
import torch
import tvm
from tvm import relay
import tvm.contrib.graph_runtime as runtime

def fn(x):
    y = (x - 1).long()
    y = y.to(dtype=torch.float32)
    y = y[:, 0]
    return y

jit = torch.jit.trace(fn, (torch.ones(4, 5, dtype=torch.int64),))
torch.jit.save(jit, "test.jit")

jit = torch.jit.load("test.jit", map_location=torch.device('cpu'))
jit.eval()

inputs = torch.randint(low=0, high=10, size=(4, 5), dtype=torch.int64)
print(jit(inputs))


shape_list = [('input', [4, 5])]

mod, params = relay.frontend.pytorch.from_pytorch(jit,
                                                  shape_list,
                                                  default_dtype="float32")

with tvm.transform.PassContext(opt_level=3):
    json, lib, params = relay.build(mod, target="llvm", params=params)

ctx = tvm.cpu(0)
inputs = tvm.nd.array(inputs.cpu().numpy().astype(np.int64), ctx)
runtime = tvm.contrib.graph_runtime.create(json, lib, ctx)
runtime.set_input(**params)
runtime.set_input('input', inputs)
runtime.run()
tvm_result = runtime.get_output(0).asnumpy()
print(tvm_result)
```

There is no type of information in the JIT file, seems TVM cannot support the situation (load from JIT file) yet.

**Comment by masahi** [comment]
I don't know what to do about it, other than wait for PyTorch people to fix dtype saving. For quantized models, I added a workaround, but I don't know if we can come up with a similar workaround (piggy back on to Relay's type inference).

For reference, here is Torchscript IR with or without save/load:

without save/load
```
graph(%x : Long(4:5, 5:1)):
  %1 : Long() = prim::Constant[value={1}]() # test.py:8:0
  %2 : int = prim::Constant[value=1]() # test.py:8:0
  %3 : Long(4:5, 5:1) = aten::sub(%x, %1, %2) # test.py:8:0
  %4 : int = prim::Constant[value=4]() # test.py:8:0
  %5 : bool = prim::Constant[value=0]() # test.py:8:0
  %6 : bool = prim::Constant[value=0]() # test.py:8:0
  %7 : None = prim::Constant()
  %y.1 : Long(4:5, 5:1) = aten::to(%3, %4, %5, %6, %7) # test.py:8:0
  %9 : int = prim::Constant[value=6]() # test.py:9:0
  %10 : bool = prim::Constant[value=0]() # test.py:9:0
  %11 : bool = prim::Constant[value=0]() # test.py:9:0
  %12 : None = prim::Constant()
  %y : Float(4:5, 5:1) = aten::to(%y.1, %9, %10, %11, %12) # test.py:9:0
  %14 : int = prim::Constant[value=0]() # test.py:10:0
  %15 : int = prim::Constant[value=0]() # test.py:10:0
  %16 : int = prim::Constant[value=9223372036854775807]() # test.py:10:0
  %17 : int = prim::Constant[value=1]() # test.py:10:0
  %18 : Float(4:5, 5:1) = aten::slice(%y, %14, %15, %16, %17) # test.py:10:0
  %19 : int = prim::Constant[value=1]() # test.py:10:0
  %20 : int = prim::Constant[value=0]() # test.py:10:0
  %21 : Float(4:5) = aten::select(%18, %19, %20) # test.py:10:0
  return (%21)
```

```
graph(%self : __torch__.PlaceholderModule,
      %x.1 : Tensor):
  %2 : None = prim::Constant() # :0:0
  %3 : bool = prim::Constant[value=0]() # test.py:8:0
  %4 : Tensor = prim::Constant[value={1}]() # test.py:8:0
  %5 : int = prim::Constant[value=1]() # test.py:8:0
  %6 : int = prim::Constant[value=4]() # test.py:8:0
  %7 : int = prim::Constant[value=6]() # test.py:9:0
  %8 : int = prim::Constant[value=0]() # test.py:10:0
  %9 : int = prim::Constant[value=9223372036854775807]() # test.py:10:0
  %10 : Tensor = aten::sub(%x.1, %4, %5) # test.py:8:0
  %y.1 : Tensor = aten::to(%10, %6, %3, %3, %2) # test.py:8:0
  %y0.1 : Tensor = aten::to(%y.1, %7, %3, %3, %2) # test.py:9:0
  %13 : Tensor = aten::slice(%y0.1, %8, %8, %9, %5) # test.py:10:0
  %14 : Tensor = aten::select(%13, %5, %8) # test.py:10:0
  return (%14)

```

**Comment by nolanliou** [comment]
@masahi 
There are some problems with the type/shape inference when converting the PyTorch model.

Sample code to reproduce.
```
import numpy as np
import torch
import tvm
from tvm import relay
import tvm.contrib.graph_runtime as runtime

def fn(x):
    x /= x.shape[-1]
    return x

jit = torch.jit.trace(fn, (torch.ones(4, 5, dtype=torch.int64),))

inputs = torch.randint(low=0, high=10, size=(4, 5), dtype=torch.float32)
print(jit(inputs))


shape_list = [('input', [4, 5])]

mod, params = relay.frontend.pytorch.from_pytorch(jit,
                                                  shape_list,
                                                  default_dtype="float32")

with tvm.transform.PassContext(opt_level=3):
    json, lib, params = relay.build(mod, target="llvm", params=params)

ctx = tvm.cpu(0)
inputs = tvm.nd.array(inputs.cpu().numpy().astype(np.int64), ctx)
runtime = tvm.contrib.graph_runtime.create(json, lib, ctx)
runtime.set_input(**params)
runtime.set_input('input', inputs)
runtime.run()
tvm_result = runtime.get_output(0).asnumpy()
print(tvm_result)
```

**Comment by masahi** [comment]
Is this the error you are getting? It is coming from PyTorch during tracing, not TVM.

```
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    jit = torch.jit.trace(fn, (torch.ones(4, 5, dtype=torch.int64),))
  File "/home/masa/projects/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 980, in trace
    _force_outplace)
  File "test.py", line 8, in fn
    x /= x.shape[-1]
RuntimeError: Integer division of tensors using div or / is no longer supported, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.
```

**Comment by nolanliou** [comment]
Nope, I use PyTorch 1.3.1. The error is 
```
Error(s) have occurred. The program has been annotated with them:

In `main`:
v0.0.4
fn (%input: Tensor[(4, 5), int64]) {
  %0 = cast(%input, dtype="float32");
  divide(%0, 5) an internal invariant was violated while typechecking your program [10:09:50] /data00/liuqi/code/tvm/src/relay/op/type_relations.cc:107: Check failed: t0->dtype == t1->dtype (float32 vs. int64) :
;
}
```

**Comment by masahi** [comment]
ok reproduced on torch 1.4

First, this is the input Torchscript IR:
```
graph(%x : Long(4, 5)):
  %1 : int = prim::Constant[value=1]() # test.py:8:0
  %2 : int = aten::size(%x, %1) # test.py:8:0
  %3 : Long() = prim::NumToTensor(%2)
  %4 : Long(4, 5) = aten::div_(%x, %3) # test.py:8:0
  return (%4)
```

It seems this is due to the unclear behavior of `torch.result_type`. Even though both lhs and rhs are clearly int64, result_type can return float32:

```
import torch
import numpy as np

lhs = torch.zeros((), dtype=torch.int64)
rhs = 5 * np.ones([]).astype("int64")  # what prim::NumToTensor(5) above converts to in our frontend

print(torch.result_type(lhs, 5))
print(torch.result_type(lhs, rhs))
```
This is the output:
```
torch.int64
torch.float32
```

Since PyTorch decides that float32 is the right type, unnecessary cast is introduced, giving the error above.

cc @t-vi @siju-samuel What should we do about it?

**Comment by t-vi** [comment]
Sorry, I completely missed the report before. 
As @masahi notes, PyTorch has stopped supporting the 1.3/1.4 behaviour there and will introduce semantically different behaviour in a future version (I would expect 1.8 or 1.9).

I would be hesitant to support the old way at all, it will cause us pain in a matter of a few months, when we need to pile on magic to decide between the old and new behaviour.
We might add a warning to "div" when used with integers and PyTorch < 1.5 or so (even though I'm not sure what happens if you JIT programs in 1.4 and load with newer PyTorch).

**Comment by t-vi** [comment]
@nolanliou Thank you for reporting this!
I know it's not a real fix, but recent versions of HF transformers library and PyTorch 1.6 are known to work with TVM (I used that combination for the post on the TVM blog).

**Comment by masahi** [comment]
@t-vi to be clear, @nolanliou's problem is not about div op being applied to integers (it is another story), the same error would happen if it is add or mul.

`torch.result_type` is confused with one of the inputs being numpy scalar of type np.int64, and it returns float32 when both lhs and rhs are clearly int64.

**Comment by masahi** [comment]
I want to update our CI (which is at PyTorch 1.4) and make 1.6 support official, but quantization is broken with PyTorch 1.6. See https://github.com/pytorch/pytorch/issues/42497. I thought I'd wait until they fix it, rather than introducing ugly workaround on our end.

**Comment by t-vi** [comment]
> `torch.result_type` is confused with one of the inputs being numpy scalar of type np.int64, and it returns float32 when both lhs and rhs are clearly int64

No it is not. The quotient of int64 is very reasonably float32.

**Comment by masahi** [comment]
oh I've just tried the above script (reproduced below) on torch 1.6, and it seems they fixed it:

```
import torch
import numpy as np

lhs = torch.zeros((), dtype=torch.int64)
rhs = 5 * np.ones([]).astype("int64")  # what prim::NumToTensor(5) above converts to in our frontend

print(torch.result_type(lhs, 5))
print(torch.result_type(lhs, rhs))
```
Output
```
torch.int64
torch.int64
```
