### ISSUE TITLE
KeyError: 'unroll_kw' while auto tuning Bug ??

### ISSUE THREAD

**Issue by ashuezy** [apache/incubator-tvm#6404]
I am using the script given here.

https://raw.githubusercontent.com/apache/incubator-tvm/v0.6/tutorials/autotvm/tune_relay_x86.py

```
2020-09-07 10:11:32,985 INFO Benchmarking layout transformation successful.
2020-09-07 10:11:33,053 INFO Start to run PBQP algorithm...
2020-09-07 10:11:33,399 INFO Finished PBQPExecutor run. Got sub-optimal solution.
2020-09-07 10:11:33,404 INFO Writing optimal schedules to mxnet_graph_opt.log successfully.
Compile...
Traceback (most recent call last):

  File "convert.py", line 238, in <module>
    tune_and_evaluate(tuning_option)

  File "convert.py", line 211, in tune_and_evaluate
    graph, lib, params = relay.build_module.build(mod, target=target, params=params)

  File "/home/xyz/Desktop/tvm/tvm_0.6.1/python/tvm/relay/build_module.py", line 244, in build
    graph_json, mod, params = bld_mod.build(func, target, target_host, params)

  File "/home/xyz/Desktop/tvm/tvm_0.6.1/python/tvm/relay/build_module.py", line 109, in build
    self._build(func, target, target_host)

  File "/home/xyz/Desktop/tvm/tvm_0.6.1/python/tvm/_ffi/_ctypes/function.py", line 207, in __call__
    raise get_last_ffi_error()

tvm._ffi.base.TVMError: Traceback (most recent call last):
  [bt] (8) /home/xyz/Desktop/tvm/tvm_0.6.1/build/libtvm.so(tvm::relay::backend::GraphRuntimeCodegen::VisitExpr(tvm::relay::Expr const&)+0x4c5) [0x7f4f10e71b95]
  [bt] (7) /home/xyz/Desktop/tvm/tvm_0.6.1/build/libtvm.so(tvm::relay::backend::GraphRuntimeCodegen::VisitExpr_(tvm::relay::CallNode const*)+0x703) [0x7f4f10e730b3]
  [bt] (6) /home/xyz/Desktop/tvm/tvm_0.6.1/build/libtvm.so(tvm::relay::backend::GraphRuntimeCodegen::VisitExpr(tvm::relay::Expr const&)+0x4c5) [0x7f4f10e71b95]
  [bt] (5) /home/xyz/Desktop/tvm/tvm_0.6.1/build/libtvm.so(tvm::relay::backend::GraphRuntimeCodegen::VisitExpr_(tvm::relay::CallNode const*)+0x533) [0x7f4f10e72ee3]
  [bt] (4) /home/xyz/Desktop/tvm/tvm_0.6.1/build/libtvm.so(+0x104dda6) [0x7f4f10e4eda6]
  [bt] (3) /home/xyz/Desktop/tvm/tvm_0.6.1/build/libtvm.so(tvm::relay::CompileEngineImpl::Lower(tvm::relay::CCacheKey const&)+0x10) [0x7f4f10e5b620]
  [bt] (2) /home/xyz/Desktop/tvm/tvm_0.6.1/build/libtvm.so(tvm::relay::CompileEngineImpl::LowerInternal(tvm::relay::CCacheKey const&)+0x352) [0x7f4f10e5aa72]
  [bt] (1) /home/xyz/Desktop/tvm/tvm_0.6.1/build/libtvm.so(tvm::relay::ScheduleGetter::Create(tvm::relay::Function const&)+0xad9) [0x7f4f10e57709]
  [bt] (0) /home/xyz/Desktop/tvm/tvm_0.6.1/build/libtvm.so(+0x11a5b63) [0x7f4f10fa6b63]
  File "/home/xyz/Desktop/tvm/tvm_0.6.1/python/tvm/_ffi/_ctypes/function.py", line 72, in cfun
    rv = local_pyfunc(*pyargs)
  File "/home/xyz/Desktop/tvm/tvm_0.6.1/python/tvm/relay/op/nn/_nn.py", line 584, in schedule_contrib_conv2d_NCHWc
    return topi.generic.schedule_conv2d_NCHWc(outs)
  File "<decorator-gen-77>", line 2, in schedule_conv2d_NCHWc
  File "/home/xyz/Desktop/tvm/tvm_0.6.1/python/tvm/target.py", line 382, in dispatch_func
    return dispatch_dict[k](*args, **kwargs)
  File "<decorator-gen-125>", line 2, in config_dispatcher
  File "/home/xyz/Desktop/tvm/tvm_0.6.1/python/tvm/autotvm/task/dispatcher.py", line 221, in dispatch_func
    return dispatch_dict[cfg.template_key](cfg, *args, **kwargs)
  File "/home/xyz/Desktop/tvm/tvm_0.6.1/python/tvm/autotvm/task/topi_integration.py", line 487, in template_call
    return f(cfg, outs, *args, **kwargs)
  File "/home/xyz/Desktop/tvm/tvm_0.6.1/topi/python/topi/x86/conv2d.py", line 431, in _schedule_conv2d_NCHWc
    traverse(outs[0].op)
  File "/home/xyz/Desktop/tvm/tvm_0.6.1/topi/python/topi/x86/conv2d.py", line 408, in traverse
    traverse(tensor.op)
  File "/home/xyz/Desktop/tvm/tvm_0.6.1/topi/python/topi/x86/conv2d.py", line 408, in traverse
    traverse(tensor.op)
  File "/home/xyz/Desktop/tvm/tvm_0.6.1/topi/python/topi/x86/conv2d.py", line 408, in traverse
    traverse(tensor.op)
  File "/home/xyz/Desktop/tvm/tvm_0.6.1/topi/python/topi/x86/conv2d.py", line 427, in traverse
    conv2d_avx_common._schedule_conv_NCHWc(*args)
  File "/home/xyz/Desktop/tvm/tvm_0.6.1/topi/python/topi/x86/conv2d_avx_common.py", line 159, in _schedule_conv_NCHWc
    reg_n, unroll_kw = cfg["tile_ow"].size[-1], cfg["unroll_kw"].val
  File "/home/xyz/Desktop/tvm/tvm_0.6.1/python/tvm/autotvm/task/space.py", line 808, in __getitem__
    return self._entity_map[name]
KeyError: 'unroll_kw'

```

**Comment by tqchen** [comment]
THanks for reporting the problem, please open a new trouble shooting thread on https://discuss.tvm.apache.org/

**Comment by ashuezy** [comment]
@tqchen 
Thanks for replying.

Opened the thread.
https://discuss.tvm.apache.org/t/keyerror-unroll-kw-while-auto-tuning/7828
