### ISSUE TITLE
undefined symbol: VTARuntimeShutdown

### ISSUE THREAD

**Issue by tirumalnaidu** [apache/incubator-tvm#6932]
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/root/tvm/python/tvm/rpc/server.py", line 118, in _serve_loop
    _ffi_api.ServerLoop(sockfd)
  File "/home/root/tvm/python/tvm/_ffi/_ctypes/packed_func.py", line 237, in __call__
    raise get_last_ffi_error()
AttributeError: Traceback (most recent call last):
  [bt] (4) /root/tvm/build/libtvm_runtime.so(TVMFuncCall+0x37) [0xb379a4f4]
  [bt] (3) /root/tvm/build/libtvm_runtime.so(+0x8c1f8) [0xb37f71f8]
  [bt] (2) /root/tvm/build/libtvm_runtime.so(tvm::runtime::RPCServerLoop(int)+0x6b) [0xb37f6aa0]
  [bt] (1) /root/tvm/build/libtvm_runtime.so(tvm::runtime::RPCEndpoint::ServerLoop()+0x13f) [0xb37e44f0]
  [bt] (0) /root/tvm/build/libtvm_runtime.so(+0x2d340) [0xb3798340]
  File "/home/root/tvm/python/tvm/_ffi/_ctypes/packed_func.py", line 81, in cfun
    rv = local_pyfunc(*pyargs)
  File "/home/root/tvm/vta/python/vta/exec/rpc_server.py", line 84, in server_shutdown
    runtime_dll[0].VTARuntimeShutdown()
  File "/usr/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/root/tvm/vta/python/vta/../../../build/libvta.so: undefined symbol: VTARuntimeShutdown

I am facing this error while running VTA on DE10 Nano.

**Comment by tqchen** [comment]
Thanks for asking the question, it would be great to followup on the discuss thread https://discuss.tvm.apache.org/t/error-vtaruntimeshutdown-symbol-is-undefined/6832
